# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wart-types.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10wart-types.proto\x12\nwart_types\"\x9c\x04\n\x06Series\x12\x34\n\x0b\x62ool_values\x18\x01 \x01(\x0b\x32\x1d.wart_types.Series.BoolSeriesH\x00\x12\x36\n\x0cint32_values\x18\x02 \x01(\x0b\x32\x1e.wart_types.Series.Int32SeriesH\x00\x12\x36\n\x0cint64_values\x18\x03 \x01(\x0b\x32\x1e.wart_types.Series.Int64SeriesH\x00\x12:\n\x0e\x66loat32_values\x18\x06 \x01(\x0b\x32 .wart_types.Series.Float32SeriesH\x00\x12:\n\x0e\x66loat64_values\x18\x07 \x01(\x0b\x32 .wart_types.Series.Float64SeriesH\x00\x12\x38\n\rstring_values\x18\x08 \x01(\x0b\x32\x1f.wart_types.Series.StringSeriesH\x00\x1a\x1a\n\nBoolSeries\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x08\x1a\x1b\n\x0bInt32Series\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\x1a\x1b\n\x0bInt64Series\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x03\x1a\x1d\n\rFloat32Series\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x1a\x1d\n\rFloat64Series\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x1a\x1c\n\x0cStringSeries\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\tB\x08\n\x06values\"c\n\tDataFrame\x12\x0f\n\x07headers\x18\x01 \x03(\t\x12#\n\x07\x63olumns\x18\x02 \x03(\x0b\x32\x12.wart_types.Series\x12\x14\n\x07\x63omment\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_commentb\x06proto3')



_SERIES = DESCRIPTOR.message_types_by_name['Series']
_SERIES_BOOLSERIES = _SERIES.nested_types_by_name['BoolSeries']
_SERIES_INT32SERIES = _SERIES.nested_types_by_name['Int32Series']
_SERIES_INT64SERIES = _SERIES.nested_types_by_name['Int64Series']
_SERIES_FLOAT32SERIES = _SERIES.nested_types_by_name['Float32Series']
_SERIES_FLOAT64SERIES = _SERIES.nested_types_by_name['Float64Series']
_SERIES_STRINGSERIES = _SERIES.nested_types_by_name['StringSeries']
_DATAFRAME = DESCRIPTOR.message_types_by_name['DataFrame']
Series = _reflection.GeneratedProtocolMessageType('Series', (_message.Message,), {

  'BoolSeries' : _reflection.GeneratedProtocolMessageType('BoolSeries', (_message.Message,), {
    'DESCRIPTOR' : _SERIES_BOOLSERIES,
    '__module__' : 'wart_types_pb2'
    # @@protoc_insertion_point(class_scope:wart_types.Series.BoolSeries)
    })
  ,

  'Int32Series' : _reflection.GeneratedProtocolMessageType('Int32Series', (_message.Message,), {
    'DESCRIPTOR' : _SERIES_INT32SERIES,
    '__module__' : 'wart_types_pb2'
    # @@protoc_insertion_point(class_scope:wart_types.Series.Int32Series)
    })
  ,

  'Int64Series' : _reflection.GeneratedProtocolMessageType('Int64Series', (_message.Message,), {
    'DESCRIPTOR' : _SERIES_INT64SERIES,
    '__module__' : 'wart_types_pb2'
    # @@protoc_insertion_point(class_scope:wart_types.Series.Int64Series)
    })
  ,

  'Float32Series' : _reflection.GeneratedProtocolMessageType('Float32Series', (_message.Message,), {
    'DESCRIPTOR' : _SERIES_FLOAT32SERIES,
    '__module__' : 'wart_types_pb2'
    # @@protoc_insertion_point(class_scope:wart_types.Series.Float32Series)
    })
  ,

  'Float64Series' : _reflection.GeneratedProtocolMessageType('Float64Series', (_message.Message,), {
    'DESCRIPTOR' : _SERIES_FLOAT64SERIES,
    '__module__' : 'wart_types_pb2'
    # @@protoc_insertion_point(class_scope:wart_types.Series.Float64Series)
    })
  ,

  'StringSeries' : _reflection.GeneratedProtocolMessageType('StringSeries', (_message.Message,), {
    'DESCRIPTOR' : _SERIES_STRINGSERIES,
    '__module__' : 'wart_types_pb2'
    # @@protoc_insertion_point(class_scope:wart_types.Series.StringSeries)
    })
  ,
  'DESCRIPTOR' : _SERIES,
  '__module__' : 'wart_types_pb2'
  # @@protoc_insertion_point(class_scope:wart_types.Series)
  })
_sym_db.RegisterMessage(Series)
_sym_db.RegisterMessage(Series.BoolSeries)
_sym_db.RegisterMessage(Series.Int32Series)
_sym_db.RegisterMessage(Series.Int64Series)
_sym_db.RegisterMessage(Series.Float32Series)
_sym_db.RegisterMessage(Series.Float64Series)
_sym_db.RegisterMessage(Series.StringSeries)

DataFrame = _reflection.GeneratedProtocolMessageType('DataFrame', (_message.Message,), {
  'DESCRIPTOR' : _DATAFRAME,
  '__module__' : 'wart_types_pb2'
  # @@protoc_insertion_point(class_scope:wart_types.DataFrame)
  })
_sym_db.RegisterMessage(DataFrame)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERIES._serialized_start=33
  _SERIES._serialized_end=573
  _SERIES_BOOLSERIES._serialized_start=387
  _SERIES_BOOLSERIES._serialized_end=413
  _SERIES_INT32SERIES._serialized_start=415
  _SERIES_INT32SERIES._serialized_end=442
  _SERIES_INT64SERIES._serialized_start=444
  _SERIES_INT64SERIES._serialized_end=471
  _SERIES_FLOAT32SERIES._serialized_start=473
  _SERIES_FLOAT32SERIES._serialized_end=502
  _SERIES_FLOAT64SERIES._serialized_start=504
  _SERIES_FLOAT64SERIES._serialized_end=533
  _SERIES_STRINGSERIES._serialized_start=535
  _SERIES_STRINGSERIES._serialized_end=563
  _DATAFRAME._serialized_start=575
  _DATAFRAME._serialized_end=674
# @@protoc_insertion_point(module_scope)
