# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wart-storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import wart_types_pb2 as wart__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12wart-storage.proto\x12\x0cwart_storage\x1a\x10wart-types.proto\"E\n\x12\x43hoiceNodesRequest\x12\x12\n\nspace_name\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\x05\"p\n\x10\x46\x65tchNodeRequest\x12\x12\n\nspace_name\x18\x01 \x01(\t\x12\x10\n\x06\x61s_int\x18\x02 \x01(\x03H\x00\x12\x10\n\x06\x61s_str\x18\x03 \x01(\tH\x00\x12\x0b\n\x03tag\x18\x04 \x01(\t\x12\x0c\n\x04keys\x18\x05 \x03(\tB\t\n\x07node_id\"\x88\x01\n\x15\x46\x65tchNeighborsRequest\x12\x12\n\nspace_name\x18\x01 \x01(\t\x12\x10\n\x06\x61s_int\x18\x02 \x01(\x03H\x00\x12\x10\n\x06\x61s_str\x18\x03 \x01(\tH\x00\x12\x0b\n\x03tag\x18\x04 \x01(\t\x12\x0c\n\x04keys\x18\x05 \x03(\t\x12\x11\n\treversely\x18\x06 \x01(\x08\x42\t\n\x07node_id\"\x93\x01\n\x0fStorageResponse\x12\x12\n\nspace_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x0f\n\x07latency\x18\x03 \x01(\x03\x12\x12\n\nerror_code\x18\x04 \x01(\x05\x12\x11\n\terror_msg\x18\x05 \x01(\t\x12#\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x15.wart_types.DataFrame2\xff\x01\n\x0bWartStorage\x12N\n\x0b\x43hoiceNodes\x12 .wart_storage.ChoiceNodesRequest\x1a\x1d.wart_storage.StorageResponse\x12J\n\tFetchNode\x12\x1e.wart_storage.FetchNodeRequest\x1a\x1d.wart_storage.StorageResponse\x12T\n\x0e\x46\x65tchNeighbors\x12#.wart_storage.FetchNeighborsRequest\x1a\x1d.wart_storage.StorageResponseb\x06proto3')



_CHOICENODESREQUEST = DESCRIPTOR.message_types_by_name['ChoiceNodesRequest']
_FETCHNODEREQUEST = DESCRIPTOR.message_types_by_name['FetchNodeRequest']
_FETCHNEIGHBORSREQUEST = DESCRIPTOR.message_types_by_name['FetchNeighborsRequest']
_STORAGERESPONSE = DESCRIPTOR.message_types_by_name['StorageResponse']
ChoiceNodesRequest = _reflection.GeneratedProtocolMessageType('ChoiceNodesRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHOICENODESREQUEST,
  '__module__' : 'wart_storage_pb2'
  # @@protoc_insertion_point(class_scope:wart_storage.ChoiceNodesRequest)
  })
_sym_db.RegisterMessage(ChoiceNodesRequest)

FetchNodeRequest = _reflection.GeneratedProtocolMessageType('FetchNodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHNODEREQUEST,
  '__module__' : 'wart_storage_pb2'
  # @@protoc_insertion_point(class_scope:wart_storage.FetchNodeRequest)
  })
_sym_db.RegisterMessage(FetchNodeRequest)

FetchNeighborsRequest = _reflection.GeneratedProtocolMessageType('FetchNeighborsRequest', (_message.Message,), {
  'DESCRIPTOR' : _FETCHNEIGHBORSREQUEST,
  '__module__' : 'wart_storage_pb2'
  # @@protoc_insertion_point(class_scope:wart_storage.FetchNeighborsRequest)
  })
_sym_db.RegisterMessage(FetchNeighborsRequest)

StorageResponse = _reflection.GeneratedProtocolMessageType('StorageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGERESPONSE,
  '__module__' : 'wart_storage_pb2'
  # @@protoc_insertion_point(class_scope:wart_storage.StorageResponse)
  })
_sym_db.RegisterMessage(StorageResponse)

_WARTSTORAGE = DESCRIPTOR.services_by_name['WartStorage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHOICENODESREQUEST._serialized_start=54
  _CHOICENODESREQUEST._serialized_end=123
  _FETCHNODEREQUEST._serialized_start=125
  _FETCHNODEREQUEST._serialized_end=237
  _FETCHNEIGHBORSREQUEST._serialized_start=240
  _FETCHNEIGHBORSREQUEST._serialized_end=376
  _STORAGERESPONSE._serialized_start=379
  _STORAGERESPONSE._serialized_end=526
  _WARTSTORAGE._serialized_start=529
  _WARTSTORAGE._serialized_end=784
# @@protoc_insertion_point(module_scope)
